version: '3.8'

services:
  frontend:
    build: ./FRONT
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./BACK
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=brainyquiz-database
      - DB_PORT=5432
      - DB_USER=brainy
      - DB_PASSWORD=brainy
      - DB_NAME=brainy

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=brainy
      - POSTGRES_PASSWORD=brainy
      - POSTGRES_DB=brainy
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
